language: go

env:
  global:
    - TMPDIR=/tmp

go:
  - 1.10.x
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test ./fanfou -v -covermode=atomic -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
